title: Documentation Draft - Title Goes Here
description: Documentation draft Description goes here
theme: just-the-docs

url: https://Paveljolak.github.io/my-docs

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/Paveljolak/my-docs
